# Notebook Intro:

In this notebook, I import the test data and perform basic clean (review nulls and datatypes), similar to what was performed in notebook 1a. 

I then output the cleaned data to a csv so other notebooks can use the clean test data for models for final submission.

Note that the data dictionary is [here](http://jse.amstat.org/v19n3/decock/DataDocumentation.txt).

In [1]:
# imports

import numpy as np
import pandas as pd

In [2]:
# import test data
filepath = '../datasets/Original/test.csv'

test = pd.read_csv(filepath)
test.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type
0,2658,902301120,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2006,WD
1,2718,905108090,90,RL,NaN,9662,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2006,WD
2,2414,528218130,60,RL,58.0,17104,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,9,2006,New
3,1989,902207150,30,RM,60.0,8520,Pave,NaN,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2007,WD
4,625,535105100,20,RL,NaN,9500,Pave,NaN,IR1,Lvl,...,0,185,0,NaN,NaN,NaN,0,7,2009,WD

In [3]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 80 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               878 non-null    int64
 1   PID              878 non-null    int64
 2   MS SubClass      878 non-null    int64
 3   MS Zoning        878 non-null    object
 4   Lot Frontage     718 non-null    float64
 5   Lot Area         878 non-null    int64
 6   Street           878 non-null    object
 7   Alley            58 non-null     object
 8   Lot Shape        878 non-null    object
 9   Land Contour     878 non-null    object
 10  Utilities        878 non-null    object
 11  Lot Config       878 non-null    object
 12  Land Slope       878 non-null    object
 13  Neighborhood     878 non-null    object
 14  Condition 1      878 non-null    object
 15  Condition 2      878 non-null    object
 16  Bldg Type        878 non-null    object
 17  House Style      878 non-null    object
 18  Overall Qual     878 non-null    int64
 19  Overall Cond     878 non-null    int64
 20  Year Built       878 non-null    int64
 21  Year Remod/Add   878 non-null    int64
 22  Roof Style       878 non-null    object
 23  Roof Matl        878 non-null    object
 24  Exterior 1st     878 non-null    object
 25  Exterior 2nd     878 non-null    object
 26  Mas Vnr Type     877 non-null    object
 27  Mas Vnr Area     877 non-null    float64
 28  Exter Qual       878 non-null    object
 29  Exter Cond       878 non-null    object
 30  Foundation       878 non-null    object
 31  Bsmt Qual        853 non-null    object
 32  Bsmt Cond        853 non-null    object
 33  Bsmt Exposure    853 non-null    object
 34  BsmtFin Type 1   853 non-null    object
 35  BsmtFin SF 1     878 non-null    int64
 36  BsmtFin Type 2   853 non-null    object
 37  BsmtFin SF 2     878 non-null    int64
 38  Bsmt Unf SF      878 non-null    int64
 39  Total Bsmt SF    878 non-null    int64
 40  Heating          878 non-null    object
 41  Heating QC       878 non-null    object
 42  Central Air      878 non-null    object
 43  Electrical       877 non-null    object
 44  1st Flr SF       878 non-null    int64
 45  2nd Flr SF       878 non-null    int64
 46  Low Qual Fin SF  878 non-null    int64
 47  Gr Liv Area      878 non-null    int64
 48  Bsmt Full Bath   878 non-null    int64
 49  Bsmt Half Bath   878 non-null    int64
 50  Full Bath        878 non-null    int64
 51  Half Bath        878 non-null    int64
 52  Bedroom AbvGr    878 non-null    int64
 53  Kitchen AbvGr    878 non-null    int64
 54  Kitchen Qual     878 non-null    object
 55  TotRms AbvGrd    878 non-null    int64
 56  Functional       878 non-null    object
 57  Fireplaces       878 non-null    int64
 58  Fireplace Qu     456 non-null    object
 59  Garage Type      834 non-null    object
 60  Garage Yr Blt    833 non-null    float64
 61  Garage Finish    833 non-null    object
 62  Garage Cars      878 non-null    int64
 63  Garage Area      878 non-null    int64
 64  Garage Qual      833 non-null    object
 65  Garage Cond      833 non-null    object
 66  Paved Drive      878 non-null    object
 67  Wood Deck SF     878 non-null    int64
 68  Open Porch SF    878 non-null    int64
 69  Enclosed Porch   878 non-null    int64
 70  3Ssn Porch       878 non-null    int64
 71  Screen Porch     878 non-null    int64
 72  Pool Area        878 non-null    int64
 73  Pool QC          4 non-null      object
 74  Fence            172 non-null    object
 75  Misc Feature     41 non-null     object
 76  Misc Val         878 non-null    int64
 77  Mo Sold          878 non-null    int64
 78  Yr Sold          878 non-null    int64
 79  Sale Type        878 non-null    object
dtypes: float64(3), int64(35), object(42)
memory usage: 548.9+ KB

In [4]:
# function to convert missing values to a selected value

def na_to_replacement_value(dataframe,list_of_column_names,replaced_value):
    for column in list_of_column_names:
        dataframe[column] = dataframe[column].replace(np.nan,replaced_value)          
    return dataframe

# perform function on the following columns and replace with none
# note that all columns have type object 

columns_na_to_none = ['Pool QC','Misc Feature','Alley','Fence','Bsmt Qual','Bsmt Cond','Bsmt Exposure','BsmtFin Type 1','BsmtFin Type 2','Fireplace Qu','Garage Type','Garage Finish','Garage Qual','Garage Cond']
test = na_to_replacement_value(test,columns_na_to_none,'none')

# convert the columns with missing values and float data types to 0

columns_na_to_0 = ['Lot Frontage','Garage Yr Blt']
test = na_to_replacement_value(test,columns_na_to_0,0)


test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 80 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               878 non-null    int64
 1   PID              878 non-null    int64
 2   MS SubClass      878 non-null    int64
 3   MS Zoning        878 non-null    object
 4   Lot Frontage     878 non-null    float64
 5   Lot Area         878 non-null    int64
 6   Street           878 non-null    object
 7   Alley            878 non-null    object
 8   Lot Shape        878 non-null    object
 9   Land Contour     878 non-null    object
 10  Utilities        878 non-null    object
 11  Lot Config       878 non-null    object
 12  Land Slope       878 non-null    object
 13  Neighborhood     878 non-null    object
 14  Condition 1      878 non-null    object
 15  Condition 2      878 non-null    object
 16  Bldg Type        878 non-null    object
 17  House Style      878 non-null    object
 18  Overall Qual     878 non-null    int64
 19  Overall Cond     878 non-null    int64
 20  Year Built       878 non-null    int64
 21  Year Remod/Add   878 non-null    int64
 22  Roof Style       878 non-null    object
 23  Roof Matl        878 non-null    object
 24  Exterior 1st     878 non-null    object
 25  Exterior 2nd     878 non-null    object
 26  Mas Vnr Type     877 non-null    object
 27  Mas Vnr Area     877 non-null    float64
 28  Exter Qual       878 non-null    object
 29  Exter Cond       878 non-null    object
 30  Foundation       878 non-null    object
 31  Bsmt Qual        878 non-null    object
 32  Bsmt Cond        878 non-null    object
 33  Bsmt Exposure    878 non-null    object
 34  BsmtFin Type 1   878 non-null    object
 35  BsmtFin SF 1     878 non-null    int64
 36  BsmtFin Type 2   878 non-null    object
 37  BsmtFin SF 2     878 non-null    int64
 38  Bsmt Unf SF      878 non-null    int64
 39  Total Bsmt SF    878 non-null    int64
 40  Heating          878 non-null    object
 41  Heating QC       878 non-null    object
 42  Central Air      878 non-null    object
 43  Electrical       877 non-null    object
 44  1st Flr SF       878 non-null    int64
 45  2nd Flr SF       878 non-null    int64
 46  Low Qual Fin SF  878 non-null    int64
 47  Gr Liv Area      878 non-null    int64
 48  Bsmt Full Bath   878 non-null    int64
 49  Bsmt Half Bath   878 non-null    int64
 50  Full Bath        878 non-null    int64
 51  Half Bath        878 non-null    int64
 52  Bedroom AbvGr    878 non-null    int64
 53  Kitchen AbvGr    878 non-null    int64
 54  Kitchen Qual     878 non-null    object
 55  TotRms AbvGrd    878 non-null    int64
 56  Functional       878 non-null    object
 57  Fireplaces       878 non-null    int64
 58  Fireplace Qu     878 non-null    object
 59  Garage Type      878 non-null    object
 60  Garage Yr Blt    878 non-null    float64
 61  Garage Finish    878 non-null    object
 62  Garage Cars      878 non-null    int64
 63  Garage Area      878 non-null    int64
 64  Garage Qual      878 non-null    object
 65  Garage Cond      878 non-null    object
 66  Paved Drive      878 non-null    object
 67  Wood Deck SF     878 non-null    int64
 68  Open Porch SF    878 non-null    int64
 69  Enclosed Porch   878 non-null    int64
 70  3Ssn Porch       878 non-null    int64
 71  Screen Porch     878 non-null    int64
 72  Pool Area        878 non-null    int64
 73  Pool QC          878 non-null    object
 74  Fence            878 non-null    object
 75  Misc Feature     878 non-null    object
 76  Misc Val         878 non-null    int64
 77  Mo Sold          878 non-null    int64
 78  Yr Sold          878 non-null    int64
 79  Sale Type        878 non-null    object
dtypes: float64(3), int64(35), object(42)
memory usage: 548.9+ KB

# dropping for right now while need to get 878 entries

In [5]:
#dropping for right now while need to get 878 entries
#test_clean= test.dropna()

test_clean = test

In [6]:
test_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 80 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               878 non-null    int64
 1   PID              878 non-null    int64
 2   MS SubClass      878 non-null    int64
 3   MS Zoning        878 non-null    object
 4   Lot Frontage     878 non-null    float64
 5   Lot Area         878 non-null    int64
 6   Street           878 non-null    object
 7   Alley            878 non-null    object
 8   Lot Shape        878 non-null    object
 9   Land Contour     878 non-null    object
 10  Utilities        878 non-null    object
 11  Lot Config       878 non-null    object
 12  Land Slope       878 non-null    object
 13  Neighborhood     878 non-null    object
 14  Condition 1      878 non-null    object
 15  Condition 2      878 non-null    object
 16  Bldg Type        878 non-null    object
 17  House Style      878 non-null    object
 18  Overall Qual     878 non-null    int64
 19  Overall Cond     878 non-null    int64
 20  Year Built       878 non-null    int64
 21  Year Remod/Add   878 non-null    int64
 22  Roof Style       878 non-null    object
 23  Roof Matl        878 non-null    object
 24  Exterior 1st     878 non-null    object
 25  Exterior 2nd     878 non-null    object
 26  Mas Vnr Type     877 non-null    object
 27  Mas Vnr Area     877 non-null    float64
 28  Exter Qual       878 non-null    object
 29  Exter Cond       878 non-null    object
 30  Foundation       878 non-null    object
 31  Bsmt Qual        878 non-null    object
 32  Bsmt Cond        878 non-null    object
 33  Bsmt Exposure    878 non-null    object
 34  BsmtFin Type 1   878 non-null    object
 35  BsmtFin SF 1     878 non-null    int64
 36  BsmtFin Type 2   878 non-null    object
 37  BsmtFin SF 2     878 non-null    int64
 38  Bsmt Unf SF      878 non-null    int64
 39  Total Bsmt SF    878 non-null    int64
 40  Heating          878 non-null    object
 41  Heating QC       878 non-null    object
 42  Central Air      878 non-null    object
 43  Electrical       877 non-null    object
 44  1st Flr SF       878 non-null    int64
 45  2nd Flr SF       878 non-null    int64
 46  Low Qual Fin SF  878 non-null    int64
 47  Gr Liv Area      878 non-null    int64
 48  Bsmt Full Bath   878 non-null    int64
 49  Bsmt Half Bath   878 non-null    int64
 50  Full Bath        878 non-null    int64
 51  Half Bath        878 non-null    int64
 52  Bedroom AbvGr    878 non-null    int64
 53  Kitchen AbvGr    878 non-null    int64
 54  Kitchen Qual     878 non-null    object
 55  TotRms AbvGrd    878 non-null    int64
 56  Functional       878 non-null    object
 57  Fireplaces       878 non-null    int64
 58  Fireplace Qu     878 non-null    object
 59  Garage Type      878 non-null    object
 60  Garage Yr Blt    878 non-null    float64
 61  Garage Finish    878 non-null    object
 62  Garage Cars      878 non-null    int64
 63  Garage Area      878 non-null    int64
 64  Garage Qual      878 non-null    object
 65  Garage Cond      878 non-null    object
 66  Paved Drive      878 non-null    object
 67  Wood Deck SF     878 non-null    int64
 68  Open Porch SF    878 non-null    int64
 69  Enclosed Porch   878 non-null    int64
 70  3Ssn Porch       878 non-null    int64
 71  Screen Porch     878 non-null    int64
 72  Pool Area        878 non-null    int64
 73  Pool QC          878 non-null    object
 74  Fence            878 non-null    object
 75  Misc Feature     878 non-null    object
 76  Misc Val         878 non-null    int64
 77  Mo Sold          878 non-null    int64
 78  Yr Sold          878 non-null    int64
 79  Sale Type        878 non-null    object
dtypes: float64(3), int64(35), object(42)
memory usage: 548.9+ KB

In [7]:
#note that I will need to impute data in future if any columns contain null values for features that I'm analyzing.

In [9]:
# export clean data
filepath = '../datasets/interim_files/test_clean.csv'

test_clean.to_csv(filepath,index=False)

# Notebook Summary of Work:

In this notebook, I import the test data and perform basic clean (review nulls and datatypes), similar to what was performed in notebook 1a. 

I then output the cleaned data to a csv so other notebooks can use the clean test data for models for final submission.